# Generated by Django 6.0.6 on 2026-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0010_nuclei_phase_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryresult',
            name='exposure_status',
            field=models.CharField(default='Accessible', max_length=50),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='final_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='is_verified_exposure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='redirect_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='response_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
