# Generated by Django 6.0.6 on 2026-08-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0011_directoryresult_access_status_and_more'),
        ('attacksurface', '0011_directoryresult_exposure_status_and_more'),
    ]

    operations = [
    ]
