# Generated by Django 6.0.8 on 2026-08-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0011_directoryresult_access_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsecurityresult',
            name='bimi',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
