# Generated by Django 6.0.6 on 2026-08-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0012_merge_20260807_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryresult',
            name='exposure_status',
        ),
        migrations.RemoveField(
            model_name='directoryresult',
            name='final_url',
        ),
        migrations.RemoveField(
            model_name='directoryresult',
            name='is_verified_exposure',
        ),
        migrations.RemoveField(
            model_name='directoryresult',
            name='redirect_chain',
        ),
        migrations.RemoveField(
            model_name='directoryresult',
            name='response_hash',
        ),
        migrations.AddField(
            model_name='endpointresult',
            name='auth_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpointresult',
            name='source_tool',
            field=models.CharField(default='Crawler', max_length=100),
        ),
    ]
