# Generated by Django 6.0.6 on 2026-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0012_emailsecurityresult_bimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainresult',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subdomainresult',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
