# Generated by Django 6.0.6 on 2026-08-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0013_remove_directoryresult_exposure_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpointresult',
            name='auth_required',
        ),
        migrations.RemoveField(
            model_name='endpointresult',
            name='source_tool',
        ),
    ]
