# Generated by Django 6.0.8 on 2026-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0013_subdomainresult_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomainresult',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subdomainresult',
            name='screenshot_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
