# Generated by Django 6.0.6 on 2026-08-10 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0014_remove_endpointresult_auth_required_and_more'),
        ('attacksurface', '0014_subdomainresult_location_and_more'),
    ]

    operations = [
    ]
