# Generated by Django 5.2.1 on 2026-08-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0014_subdomainresult_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksurfacescan',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
