# Generated by Django 5.2.1 on 2026-08-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0015_add_scan_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerabilityresult',
            name='owasp_category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vulnerabilityresult',
            name='owasp_rank',
            field=models.IntegerField(default=0),
        ),
    ]
