"""OWASP Top 10 (2021) category metadata."""

OWASP_CATEGORIES = [
    {
        "rank": 1,
        "id": "A01",
        "name": "Broken Access Control",
        "title": "A01:2021 – Broken Access Control",
        "description": "Restrictions on what authenticated users are allowed to do are not properly enforced.",
        "url": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
        "cwes": ["CWE-200", "CWE-284", "CWE-425", "CWE-639", "CWE-862", "CWE-863"],
    },
    {
        "rank": 2,
        "id": "A02",
        "name": "Cryptographic Failures",
        "title": "A02:2021 – Cryptographic Failures",
        "description": "Failures related to cryptography often lead to sensitive data exposure.",
        "url": "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
        "cwes": ["CWE-311", "CWE-319", "CWE-326", "CWE-327", "CWE-523"],
    },
    {
        "rank": 3,
        "id": "A03",
        "name": "Injection",
        "title": "A03:2021 – Injection",
        "description": "User-supplied data is not validated, filtered, or sanitized before being executed.",
        "url": "https://owasp.org/Top10/A03_2021-Injection/",
        "cwes": ["CWE-74", "CWE-78", "CWE-79", "CWE-89", "CWE-90", "CWE-94", "CWE-611", "CWE-943"],
    },
    {
        "rank": 4,
        "id": "A04",
        "name": "Insecure Design",
        "title": "A04:2021 – Insecure Design",
        "description": "Missing or ineffective control design — a focus on threats and design patterns.",
        "url": "https://owasp.org/Top10/A04_2021-Insecure_Design/",
        "cwes": ["CWE-209", "CWE-352", "CWE-770", "CWE-799"],
    },
    {
        "rank": 5,
        "id": "A05",
        "name": "Security Misconfiguration",
        "title": "A05:2021 – Security Misconfiguration",
        "description": "Insecure default configurations, incomplete or ad hoc configurations, open cloud storage.",
        "url": "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
        "cwes": ["CWE-16", "CWE-693", "CWE-1004"],
    },
    {
        "rank": 6,
        "id": "A06",
        "name": "Vulnerable and Outdated Components",
        "title": "A06:2021 – Vulnerable and Outdated Components",
        "description": "Components with known vulnerabilities that are no longer supported or updated.",
        "url": "https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/",
        "cwes": ["CWE-1104"],
    },
    {
        "rank": 7,
        "id": "A07",
        "name": "Identification and Authentication Failures",
        "title": "A07:2021 – Identification and Authentication Failures",
        "description": "Failures in identification and authentication, including weak credentials and session handling.",
        "url": "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/",
        "cwes": ["CWE-287", "CWE-306", "CWE-307", "CWE-521", "CWE-613", "CWE-640"],
    },
    {
        "rank": 8,
        "id": "A08",
        "name": "Software and Data Integrity Failures",
        "title": "A08:2021 – Software and Data Integrity Failures",
        "description": "Code and infrastructure that fails to protect against integrity violations.",
        "url": "https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/",
        "cwes": ["CWE-345", "CWE-353", "CWE-494", "CWE-502"],
    },
    {
        "rank": 9,
        "id": "A09",
        "name": "Security Logging and Monitoring Failures",
        "title": "A09:2021 – Security Logging and Monitoring Failures",
        "description": "Lack of security logging, detection, monitoring, and active response.",
        "url": "https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/",
        "cwes": ["CWE-778"],
    },
    {
        "rank": 10,
        "id": "A10",
        "name": "Server-Side Request Forgery (SSRF)",
        "title": "A10:2021 – Server-Side Request Forgery (SSRF)",
        "description": "Web servers fetching a remote resource without validating the user-supplied URL.",
        "url": "https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/",
        "cwes": ["CWE-918"],
    },
]

RANK_TO_CATEGORY = {c["rank"]: c for c in OWASP_CATEGORIES}
ID_TO_CATEGORY = {c["id"]: c for c in OWASP_CATEGORIES}
