# Generated by Django 6.0.6 on 2026-08-08 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owasp_scanner', '0001_initial'),
        ('targets', '0003_target_org_id_target_targets_tar_org_id_5c7443_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owaspscansession',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owasp_sessions', to='targets.target'),
        ),
    ]
